# example workflow for Coverity scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: coverity-sarif-report
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Coverity Full Scan
      uses: synopsys-sig/synopsys-action@v1.10.0
      with:
        coverity_url: ${{ vars.COVERITY_URL }}
        coverity_user: ${{ secrets.COV_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
        # coverity_project_name: ${{ github.event.repository.name }}
        # coverity_stream_name: ${{ github.event.repository.name }}-${{ github.ref_name }}
        # coverity_policy_view: 'Outstanding Issues'
        coverity_local: true
    - name: Coverity SARIF Report
      env:
        COVERITY_URL: ${{ vars.COVERITY_URL }}
        COV_USER: ${{ secrets.COV_USER }}
        COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
        COVERITY_PROJECT: ${{ github.event.repository.name }}
        COVERITY_STREAM: ${{ github.event.repository.name }}-${{ github.ref_name }}
      run: |
        env | sort
        find /home/runner/.synopsys/bridge
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
